In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from google.colab import files
uploaded = files.upload()
data= pd.read_csv("dataset2.csv")

Saving dataset2.csv to dataset2.csv

In [4]:
data['Pus cells clumps'].fillna(data['Pus cells clumps'].mode()[0], inplace=True)

/tmp/ipykernel_8309/888069267.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Pus cells clumps'].fillna(data['Pus cells clumps'].mode()[0], inplace=True)

In [5]:
data['Bacteria'].fillna(data['Bacteria'].mode()[0], inplace=True)

/tmp/ipykernel_8309/2605330781.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Bacteria'].fillna(data['Bacteria'].mode()[0], inplace=True)

In [6]:
data['Serum Creatinine'].fillna(data['Serum Creatinine'].mean(), inplace=True)

/tmp/ipykernel_8309/2698678221.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Serum Creatinine'].fillna(data['Serum Creatinine'].mean(), inplace=True)

In [7]:
data['Apetite'].fillna(data['Apetite'].mode()[0], inplace=True)

/tmp/ipykernel_8309/348316318.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Apetite'].fillna(data['Apetite'].mode()[0], inplace=True)

In [8]:
data['Chronic kidney failure'].fillna(data['Chronic kidney failure'].mode()[0], inplace=True)

/tmp/ipykernel_8309/3897703642.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Chronic kidney failure'].fillna(data['Chronic kidney failure'].mode()[0], inplace=True)

In [ ]:
print(data.isnull().sum())

Patient ID                   0
Age                          0
Blood Pressure               0
Urine Specific Gravity       0
Albumin in urine             0
Sugar in urine               0
RBC                          0
Puss cells                   0
Pus cells clumps             0
Bacteria                     0
Random blood glucose         0
Urea in blood                0
Serum Creatinine             0
Sodium in blood              0
Potassium in blood           0
Hemoglobin                   0
Packed corpuscular volume    0
WBC count                    0
RBC count                    0
Apetite                      0
Chronic kidney failure       0
dtype: int64

In [ ]:
data.describe()

,Patient ID,Age,Blood Pressure,Urine Specific Gravity,Albumin in urine,Sugar in urine,Random blood glucose,Urea in blood,Serum Creatinine,Sodium in blood,Potassium in blood,Hemoglobin,Packed corpuscular volume,WBC count,RBC count
count,15051.000000,15051.000000,15051.000000,15051.000000,15051.000000,15051.000000,15051.000000,15051.000000,15051.000000,15051.000000,15051.000000,15051.000000,15051.000000,15051.000000,15051.00000
mean,7525.000000,52.100458,93.232144,11.287820,228.358714,154.320710,157.608132,59.652501,3.224108,138.584739,5.384616,11.999568,36.842961,7624.345160,4.38249
std,4344.993786,17.554229,19.906447,1.522975,314.218358,248.575959,62.352270,42.514865,5.477954,5.823178,0.859756,2.410039,7.394153,2250.210113,1.02287
min,0.000000,2.000000,50.000000,10.000000,0.000000,0.000000,70.000000,10.000000,0.400000,120.000000,3.500000,6.000000,20.000000,3044.000000,2.50000
25%,3762.500000,45.000000,80.000000,10.190000,0.000000,0.000000,105.000000,25.000000,0.940000,135.000000,4.790000,10.000000,30.500000,5691.000000,3.50000
50%,7525.000000,55.000000,94.000000,10.240000,1.000000,1.000000,139.000000,40.000000,1.400000,139.000000,5.400000,12.000000,36.000000,7628.000000,4.50000
75%,11287.500000,65.000000,107.000000,12.350000,452.400000,200.000000,208.000000,93.550000,3.250000,143.000000,6.090000,14.000000,43.000000,9505.000000,5.30000
max,15050.000000,90.000000,180.000000,15.000000,989.900000,1000.000000,300.000000,200.000000,76.000000,150.000000,7.500000,16.000000,50.000000,11999.000000,6.00000

In [ ]:
freq= pd.DataFrame(data['Blood Pressure'].value_counts())
freq

                count
Blood Pressure
70               2036
80               1920
90               1460
60               1089
100               874
...               ...
175                 1
161                 1
151                 1
135                 1
81                  1

[93 rows x 1 columns]

finding central tendancy for blood pressure.

In [ ]:
var= (data['Blood Pressure'].std())**2  #finding variance of blood pressure
print(f'variance of blood pressure is {var}')

variance of blood pressure is 396.2666371237045

In [ ]:
iqr= (data['Blood Pressure'].quantile(0.75))-(data['Blood Pressure'].quantile(0.25)) #finding iqr of blood pressure
print(f'inter-quartile range of blood pressure is {iqr}')

inter-quartile range of blood pressure is 27.0

activity 2

In [ ]:
data.shape[0]

15051

In [9]:
bp=list()
frequency=list()
for i in range(0, data.shape[0]):
  if data['Blood Pressure'][i] not in bp:
    bp.append(data['Blood Pressure'][i])
    frequency.append(1)
  else:
    frequency[bp.index(data['Blood Pressure'][i])]+=1

print(bp)
print(frequency)

len(bp)==len(frequency)

[np.int64(178), np.int64(138), np.int64(165), np.int64(141), np.int64(175), np.int64(156), np.int64(143), np.int64(157), np.int64(171), np.int64(154), np.int64(146), np.int64(153), np.int64(130), np.int64(137), np.int64(177), np.int64(174), np.int64(144), np.int64(176), np.int64(155), np.int64(173), np.int64(161), np.int64(150), np.int64(133), np.int64(147), np.int64(158), np.int64(167), np.int64(162), np.int64(139), np.int64(168), np.int64(149), np.int64(164), np.int64(160), np.int64(180), np.int64(148), np.int64(172), np.int64(151), np.int64(132), np.int64(142), np.int64(152), np.int64(131), np.int64(159), np.int64(134), np.int64(136), np.int64(179), np.int64(170), np.int64(140), np.int64(166), np.int64(169), np.int64(145), np.int64(135), np.int64(163), np.int64(101), np.int64(105), np.int64(115), np.int64(111), np.int64(114), np.int64(113), np.int64(120), np.int64(112), np.int64(116), np.int64(110), np.int64(109), np.int64(104), np.int64(97), np.int64(118), np.int64(98), np.int64(107), np.int64(95), np.int64(103), np.int64(99), np.int64(106), np.int64(119), np.int64(108), np.int64(91), np.int64(96), np.int64(102), np.int64(93), np.int64(100), np.int64(117), np.int64(90), np.int64(94), np.int64(92), np.int64(70), np.int64(60), np.int64(80), np.int64(50), np.int64(81), np.int64(83), np.int64(86), np.int64(84), np.int64(89), np.int64(88), np.int64(87)]
[6, 4, 6, 4, 1, 3, 4, 4, 2, 9, 8, 3, 9, 9, 6, 8, 9, 5, 6, 5, 1, 10, 4, 6, 11, 4, 6, 6, 6, 3, 7, 2, 47, 2, 8, 1, 4, 5, 2, 3, 6, 7, 5, 2, 5, 47, 6, 5, 2, 1, 2, 254, 272, 242, 258, 237, 235, 287, 257, 246, 265, 238, 234, 253, 249, 236, 292, 252, 228, 244, 242, 247, 262, 255, 246, 247, 251, 874, 225, 1460, 229, 236, 2036, 1089, 1920, 88, 1, 2, 5, 5, 5, 5, 5]

True

In [10]:
# mean= sum(freq * bp)/ sum(freq)
numerator=0
denominator=0
for i in range(0, len(bp)):
  numerator+=bp[i]*frequency[i]
  denominator+= frequency[i]
mean = numerator/denominator
print(f'mean of Blood Pressure is: {mean}')

mean of Blood Pressure is: 93.23214404358514

In [11]:
bp_asc = sorted(bp)
frequency2 = list()
for i in range(0, len(bp_asc)):
  frequency2.append(frequency[bp.index(bp_asc[i])])
print(bp_asc)
print(frequency2)

[np.int64(50), np.int64(60), np.int64(70), np.int64(80), np.int64(81), np.int64(83), np.int64(84), np.int64(86), np.int64(87), np.int64(88), np.int64(89), np.int64(90), np.int64(91), np.int64(92), np.int64(93), np.int64(94), np.int64(95), np.int64(96), np.int64(97), np.int64(98), np.int64(99), np.int64(100), np.int64(101), np.int64(102), np.int64(103), np.int64(104), np.int64(105), np.int64(106), np.int64(107), np.int64(108), np.int64(109), np.int64(110), np.int64(111), np.int64(112), np.int64(113), np.int64(114), np.int64(115), np.int64(116), np.int64(117), np.int64(118), np.int64(119), np.int64(120), np.int64(130), np.int64(131), np.int64(132), np.int64(133), np.int64(134), np.int64(135), np.int64(136), np.int64(137), np.int64(138), np.int64(139), np.int64(140), np.int64(141), np.int64(142), np.int64(143), np.int64(144), np.int64(145), np.int64(146), np.int64(147), np.int64(148), np.int64(149), np.int64(150), np.int64(151), np.int64(152), np.int64(153), np.int64(154), np.int64(155), np.int64(156), np.int64(157), np.int64(158), np.int64(159), np.int64(160), np.int64(161), np.int64(162), np.int64(163), np.int64(164), np.int64(165), np.int64(166), np.int64(167), np.int64(168), np.int64(169), np.int64(170), np.int64(171), np.int64(172), np.int64(173), np.int64(174), np.int64(175), np.int64(176), np.int64(177), np.int64(178), np.int64(179), np.int64(180)]
[88, 1089, 2036, 1920, 1, 2, 5, 5, 5, 5, 5, 1460, 255, 236, 251, 229, 252, 246, 253, 236, 244, 874, 254, 247, 228, 234, 272, 242, 292, 262, 238, 265, 258, 257, 235, 237, 242, 246, 225, 249, 247, 287, 9, 3, 4, 4, 7, 1, 5, 9, 4, 6, 47, 4, 5, 4, 9, 2, 8, 6, 2, 3, 10, 1, 2, 3, 9, 6, 3, 4, 11, 6, 2, 1, 6, 2, 7, 6, 6, 4, 6, 5, 5, 2, 8, 5, 8, 1, 5, 6, 6, 2, 47]

In [12]:
# median using cf
cf=frequency2[0]
for i in range(0, len(bp_asc)):
  if cf< len(data['Blood Pressure'])/2:
    cf+=frequency2[i+1]
  else:
    break

median= bp_asc[i]
print(f'median of blood pressure is: {median}')

print(cf)
print(i)
print(len(data['Blood Pressure'])/2)

median of blood pressure is: 94
7592
15
7525.5

In [13]:
#mode= bp with highest frequency
mode_index=0
for i in range(0, len(bp)):
  if frequency[i]>frequency[mode_index]:
    mode_index=i
mode= bp[mode_index]
print(f'mode of blood pressure is: {mode}')

mode of blood pressure is: 70

In [14]:
#variance = sum(f*(x-mean)**2) / sum(f)
numerator=0
denominator=0
for i in range(0, len(bp)):
  numerator += frequency[i]*(bp[i]-mean)**2
  denominator += frequency[i]

variance=numerator/denominator
print(f'variance of blood pressure: {variance}')

variance of blood pressure: 396.24030886397674

In [15]:
#standard deviation= sq.root(variance)
std_devi= (variance)**0.5
print(f'standard deviation on blood pressure is: {std_devi}')

standard deviation on blood pressure is: 19.90578581377728

In [64]:
# For discrete frequency distribution, we need to consider frequencies.
total_observations = sum(frequency2)

# Calculate Q1
q1_position_discrete = total_observations / 4
cumulative_frequency = 0
q1_discrete = 0
for i in range(len(bp_asc)):
    cumulative_frequency += frequency2[i]
    if cumulative_frequency >= q1_position_discrete:
        q1_discrete = bp_asc[i]
        break
print(f'Q1 for discrete frequency distribution: {q1_discrete}')

# Calculate Q3
q3_position_discrete = 3 * total_observations / 4
cumulative_frequency = 0
q3_discrete = 0
for i in range(len(bp_asc)):
    cumulative_frequency += frequency2[i]
    if cumulative_frequency >= q3_position_discrete:
        q3_discrete = bp_asc[i]
        break
print(f'Q3 for discrete frequency distribution: {q3_discrete}')

iqr_discrete = q3_discrete - q1_discrete
print(f'Inter-quartile range for discrete frequency distribution: {iqr_discrete}')

Q1 for discrete frequency distribution: 80
Q3 for discrete frequency distribution: 107
Inter-quartile range for discrete frequency distribution: 27

In [17]:
print(max(data['Blood Pressure']))
print(min(data['Blood Pressure']))

180
50

In [18]:
# number of classes is 10. therefore width of each class will be (180-50)/10 = 13
bins=[50, 63, 76, 90, 103, 116, 129, 142, 155, 168, 180]
labels=['50-63', '63-76', '76-89', '89-102', '102-115', '115-128', '128-141', '141-154', '154-167', '167-180']
data['blood presssure grp']=pd.cut(data['Blood Pressure'], bins=bins, labels=labels, right=False)
data.head()

,Patient ID,Age,Blood Pressure,Urine Specific Gravity,Albumin in urine,Sugar in urine,RBC,Puss cells,Pus cells clumps,Bacteria,...,Serum Creatinine,Sodium in blood,Potassium in blood,Hemoglobin,Packed corpuscular volume,WBC count,RBC count,Apetite,Chronic kidney failure,blood presssure grp
0,0,48,178,10.10,2.0,2,abnormal,abnormal,present,present,...,9.08,124.0,6.0,8.0,25.0,11319,3.8,poor,yes,167-180
1,1,7,138,10.14,1.0,4,abnormal,abnormal,present,present,...,7.88,133.0,6.8,11.0,27.0,11018,2.9,poor,yes,128-141
2,2,62,165,10.14,2.0,5,abnormal,abnormal,present,present,...,12.89,130.0,6.0,8.0,27.0,5479,4.4,poor,yes,154-167
3,3,48,141,10.07,4.0,4,abnormal,abnormal,present,present,...,5.02,133.0,5.8,11.0,35.0,7817,3.2,poor,yes,128-141
4,4,51,175,10.15,4.0,5,abnormal,abnormal,present,present,...,7.32,132.0,6.8,9.0,30.0,3055,3.9,poor,yes,167-180

In [20]:
#bp_grp=list()
#frequency_grp=list()
for i in range(0, data.shape[0]):
  if data['blood presssure grp'][i] not in bp_grp:
    bp_grp.append(data['blood presssure grp'][i])
    frequency_grp.append(1)
  else:
    frequency_grp[bp_grp.index(data['blood presssure grp'][i])]+=1

grp_dict= {
    'Grouped BP': bp_grp,
    'Frequency': frequency_grp
}

print(bp_grp)
print(frequency_grp)

data_grp= pd.DataFrame(grp_dict)
data_grp

['167-180', '128-141', '154-167', '141-154', nan, '89-102', '102-115', '115-128', '63-76', '50-63', '76-89']
[59, 103, 64, 64, 47, 5037, 3262, 1254, 2036, 1177, 1948]

   Grouped BP  Frequency
0     167-180         59
1     128-141        103
2     154-167         64
3     141-154         64
4         NaN         47
5      89-102       5037
6     102-115       3262
7     115-128       1254
8       63-76       2036
9       50-63       1177
10      76-89       1948

In [21]:
data[data['blood presssure grp'].isnull()][['Blood Pressure', 'blood presssure grp']]

       Blood Pressure blood presssure grp
58                180                 NaN
165               180                 NaN
201               180                 NaN
8296              180                 NaN
8416              180                 NaN
8563              180                 NaN
8644              180                 NaN
8701              180                 NaN
8839              180                 NaN
8927              180                 NaN
9015              180                 NaN
9103              180                 NaN
9191              180                 NaN
9369              180                 NaN
9774              180                 NaN
9894              180                 NaN
10100             180                 NaN
10339             180                 NaN
10744             180                 NaN
10864             180                 NaN
11011             180                 NaN
11092             180                 NaN
11149             180                 NaN
11301             180                 NaN
11706             180                 NaN
11826             180                 NaN
11973             180                 NaN
12054             180                 NaN
12111             180                 NaN
12263             180                 NaN
12668             180                 NaN
12788             180                 NaN
12935             180                 NaN
13016             180                 NaN
13073             180                 NaN
13225             180                 NaN
13630             180                 NaN
13750             180                 NaN
13897             180                 NaN
13978             180                 NaN
14035             180                 NaN
14182             180                 NaN
14587             180                 NaN
14707             180                 NaN
14854             180                 NaN
14935             180                 NaN
14992             180                 NaN

In [22]:
data['blood presssure grp'].fillna('167-180', inplace=True)

/tmp/ipykernel_8309/3921610684.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['blood presssure grp'].fillna('167-180', inplace=True)

In [23]:
bp_grp=list()
frequency_grp=list()
for i in range(0, data.shape[0]):
  if data['blood presssure grp'][i] not in bp_grp:
    bp_grp.append(data['blood presssure grp'][i])
    frequency_grp.append(1)
  else:
    frequency_grp[bp_grp.index(data['blood presssure grp'][i])]+=1

grp_dict= {
    'Grouped BP': bp_grp,
    'Frequency': frequency_grp
}

print(bp_grp)
print(frequency_grp)

data_grp= pd.DataFrame(grp_dict)
data_grp

['167-180', '128-141', '154-167', '141-154', '89-102', '102-115', '115-128', '63-76', '50-63', '76-89']
[106, 103, 64, 64, 5037, 3262, 1254, 2036, 1177, 1948]

  Grouped BP  Frequency
0    167-180        106
1    128-141        103
2    154-167         64
3    141-154         64
4     89-102       5037
5    102-115       3262
6    115-128       1254
7      63-76       2036
8      50-63       1177
9      76-89       1948

In [28]:
from pandas.api.types import CategoricalDtype

# Define the custom order for the blood pressure groups
bp_group_order = ['50-63', '63-76', '76-89', '89-102', '102-115', '115-128', '128-141', '141-154', '154-167', '167-180']

# Create a CategoricalDtype with the specified order
cat_type = CategoricalDtype(categories=bp_group_order, ordered=True)

# Apply the categorical type to the 'Grouped BP' column
data_grp['Grouped BP'] = data_grp['Grouped BP'].astype(cat_type)

# Sort the DataFrame by the 'Grouped BP' column
data_grp_asc = data_grp.sort_values(by='Grouped BP')

display(data_grp_asc)

  Grouped BP  Frequency
8      50-63       1177
7      63-76       2036
9      76-89       1948
4     89-102       5037
5    102-115       3262
6    115-128       1254
1    128-141        103
3    141-154         64
2    154-167         64
0    167-180        106

In [37]:
# Reset the index of the sorted DataFrame
data_grp_asc = data_grp_asc.reset_index(drop=True)
display(data_grp_asc)

  Grouped BP  Frequency
0      50-63       1177
1      63-76       2036
2      76-89       1948
3     89-102       5037
4    102-115       3262
5    115-128       1254
6    128-141        103
7    141-154         64
8    154-167         64
9    167-180        106

In [38]:
data_grp_asc['lower limit']= data_grp_asc['Grouped BP'].str.split('-').str[0].astype(int)
data_grp_asc['upper limit']= data_grp_asc['Grouped BP'].str.split('-').str[1].astype(int)
data_grp_asc

  Grouped BP  Frequency  lower limit  upper limit
0      50-63       1177           50           63
1      63-76       2036           63           76
2      76-89       1948           76           89
3     89-102       5037           89          102
4    102-115       3262          102          115
5    115-128       1254          115          128
6    128-141        103          128          141
7    141-154         64          141          154
8    154-167         64          154          167
9    167-180        106          167          180

In [41]:
# grouped mean = sum(freq* midpoint)/ sum(freq)
numerator=0
denominator=0
for i in range(0, len(bp_grp)):
  numerator += data_grp_asc['Frequency'][i] * ((data_grp_asc['upper limit'][i]+data_grp_asc['lower limit'][i])/2)
  denominator += data_grp_asc['Frequency'][i]

grp_mean= numerator/denominator
print(f'grouped mean of blood pressure is: {grp_mean}')

grouped mean of blood pressure is: 93.54797023453591

In [48]:
#grouped median = lower_lim_median_class + ((class_widh/median_freq)(sum(freq)/2 - cf))
cf= 0
class_width=13
for i in range(0, len(bp_grp)):
  if cf < len(data['Blood Pressure'])/2:
    cf += data_grp_asc['Frequency'][i]
  else:
    break

median_grp= data_grp_asc['lower limit'][i] + ((class_width/ data_grp_asc['Frequency'][i])*(len(data['Blood Pressure'])/2 - cf))
print(f'median of grouped data is: {median_grp}')

median of grouped data is: 91.34932556713673

In [57]:
#grouped mode= lower_lim_median_class + (class_width)(f1-f0)/(2f1-f0-f2)
mode_class=0
for i in range(10):
  if data_grp_asc['Frequency'][i]>data_grp_asc['Frequency'][mode_class]:
    mode_class=i

numerator= class_width*(data_grp_asc['Frequency'][mode_class] - data_grp_asc['Frequency'][mode_class-1])
denominator= 2*data_grp_asc['Frequency'][mode_class] - data_grp_asc['Frequency'][mode_class-1] - data_grp_asc['Frequency'][mode_class+1]
mode_grp= data_grp_asc['lower limit'][mode_class] + numerator/denominator

print(f'Mode of grouped data: {mode_grp}')
print(mode_class)

Mode of grouped data: 97.25596217105263
3

In [60]:
#grouped variance= sum(freq * (mp - mean)**2) / sum(freq)
numerator=0
denominator=0
for i in range(10):
  midpoint= (data_grp_asc['upper limit'][i] +data_grp_asc['lower limit'][i])/2
  numerator += data_grp_asc['Frequency'][i] * (midpoint - grp_mean)**2
  denominator += data_grp_asc['Frequency'][i]

var_grp= numerator/denominator
print(f'variance of grouped data: {var_grp}')

variance of grouped data: 404.12061427750075

In [61]:
# standard deviation of grouped data = variance**0.5
std_devi_grp = var_grp**0.5
print(f'grouped standard deviation: {std_devi_grp}')

grouped standard deviation: 20.102751410627867

In [62]:
# Calculate Inter-Quartile Range (IQR) for grouped data

total_frequency = data_grp_asc['Frequency'].sum()

# Calculate Q1
q1_position = total_frequency / 4
cum_freq = 0
q1_lower_limit = 0
q1_frequency = 0
q1_cf_before = 0

for i in range(len(data_grp_asc)):
    cum_freq += data_grp_asc['Frequency'][i]
    if cum_freq >= q1_position:
        q1_lower_limit = data_grp_asc['lower limit'][i]
        q1_frequency = data_grp_asc['Frequency'][i]
        # The cumulative frequency of the class preceding the quartile class
        if i > 0:
            q1_cf_before = cum_freq - data_grp_asc['Frequency'][i]
        else:
            q1_cf_before = 0
        break

q1 = q1_lower_limit + ((q1_position - q1_cf_before) / q1_frequency) * class_width
print(f'Q1 for grouped data: {q1}')

# Calculate Q3
q3_position = 3 * total_frequency / 4
cum_freq = 0
q3_lower_limit = 0
q3_frequency = 0
q3_cf_before = 0

for i in range(len(data_grp_asc)):
    cum_freq += data_grp_asc['Frequency'][i]
    if cum_freq >= q3_position:
        q3_lower_limit = data_grp_asc['lower limit'][i]
        q3_frequency = data_grp_asc['Frequency'][i]
        # The cumulative frequency of the class preceding the quartile class
        if i > 0:
            q3_cf_before = cum_freq - data_grp_asc['Frequency'][i]
        else:
            q3_cf_before = 0
        break

q3 = q3_lower_limit + ((q3_position - q3_cf_before) / q3_frequency) * class_width
print(f'Q3 for grouped data: {q3}')

# Calculate IQR
iqr_grouped = q3 - q1
print(f'Inter-quartile range for grouped data: {iqr_grouped}')

Q1 for grouped data: 79.66876283367556
Q3 for grouped data: 106.34495708154506
Inter-quartile range for grouped data: 26.676194247869503

In [ ]:
class data_analyser:
  def __init__(self, column):
    self.column=column
    col_lst= list()
    col_freq= list()

  def find_freq(self):
    for i in range(0, data.shape[0]):
      if data[self.column][i] not in self.col_lst:
        self.col_lst.append(data[self.column][i])
        self.col_freq.append(1)
      else:
        self.col_freq[self.col_lst.index(data[self.column][i])]+=1
    print(self.col_lst)
    print(self.col_freq)

  def sort_ascending(self):
    self.col_lst_sort= sorted(self.col_lst)
    self.col_freq_sort= list()
    for i in range(0, len(self.col_lst)):
      self.col_freq_sort.append(self.col_freq[self.col_lst.index(self.col_lst_sort[i])])
    print(self.col_lst_sort)
    print(self.col_freq_sort)

  def mean(self):
    numerator=0
    denominator=0
    for i in range(0, len(self.col_lst)):
      numerator+=self.col_lst[i]*self.col_freq[i]
      denominator+= self.col_freq[i]
    mean = numerator/denominator
    print(f'mean of Blood Pressure is: {mean}')
    return mean

  def mode(self):
    mode_index=0
    for i in range(0, len(self.col_lst)):
      if self.col_freq[i]>self.col_freq[mode_index]:
        mode_index=i
    mode= self.col_lst[mode_index]
    print(f'mode of blood pressure is: {mode}')

  def median(self):
    cf=self.col_freq_sort[0]
    for i in range(0, len(self.col_lst_sort)):
      if cf< len(data['self.column'])/2:
        cf+=self.col_freq_sort[i+1]
      else:
        break
    median= bp_asc[i]
    print(f'median of blood pressure is: {median}')


  def variance(self):
    numerator=0
    denominator=0
    for i in range(0, len(self.col_lst)):
      numerator += self.col_freq[i]*(self.col_lst[i]-self.mean())**2
      denominator += self.col_freq[i]

    variance=numerator/denominator
    print(f'variance of blood pressure: {variance}')
    return variance

  def std_devi(self):
    std_devi= (self.variance())**0.5
    print(f'standard deviation on blood pressure is: {std_devi}')

  def IQR(self):
    pass